//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.IBANs = new HashSet<IBAN>();
            this.LoginLogs = new HashSet<LoginLog>();
        }
    
        public int Account_ID { get; set; }
        public string Account_name { get; set; }
        public string Account_Surname { get; set; }
        public string Account_Phone { get; set; }
        public string Account_SSN { get; set; }
        public string Account_Type { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Username { get; set; }
        public string PIN { get; set; }
    
        public virtual ICollection<IBAN> IBANs { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
    }
}
