//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBAN
    {
        public IBAN()
        {
            this.Transaction_Deposit = new HashSet<Transaction_Deposit>();
            this.Transaction_Tranfer = new HashSet<Transaction_Tranfer>();
            this.Transaction_Tranfer1 = new HashSet<Transaction_Tranfer>();
        }
    
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public int Account_ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Transaction_Deposit> Transaction_Deposit { get; set; }
        public virtual ICollection<Transaction_Tranfer> Transaction_Tranfer { get; set; }
        public virtual ICollection<Transaction_Tranfer> Transaction_Tranfer1 { get; set; }
    }
}
