//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int Log_ID { get; set; }
        public int Account_ID { get; set; }
        public System.DateTime Login_Date { get; set; }
        public Nullable<System.DateTime> Logout_Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
