//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Tranfer
    {
        public int Tran_ID { get; set; }
        public string From_Code { get; set; }
        public decimal From_Amount { get; set; }
        public string To_Code { get; set; }
        public decimal To_Amount { get; set; }
        public decimal Tran_Amount { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Tran_By { get; set; }
    
        public virtual IBAN IBAN { get; set; }
        public virtual IBAN IBAN1 { get; set; }
    }
}
