//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Deposit
    {
        public int Dep_ID { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Dep_Fee { get; set; }
        public decimal Dep_Amount { get; set; }
        public System.DateTime Dep_Date { get; set; }
        public string Dep_By { get; set; }
    
        public virtual IBAN IBAN { get; set; }
    }
}
